version: '3.4'

services:
  printme:
    image: ${DOCKER_REGISTRY-}printme
    build:
      context: .
      dockerfile: PrintMe/Dockerfile
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
